"""
DerivedDate — the problem TECHNICAL_PLAN_CORPORATE.md §0 identified as the hardest one.

A due date is a number that does not appear in the statute. s.96 says an AGM must be held
"within six months from the date of closing of the financial year". For a 31 March 2026 year-end
the answer is 30 September 2026 — a string that is nowhere in the Act, and cannot be, because the
Act is not written per company.

verifier.py's rule is: reject any answer containing a figure absent from the source. Unmodified it
would reject every correct deadline this product computes, as a fabrication.

Resolution: verify the INTERVAL, not the result.

    anchor        2026-03-31   <- a FACT the user supplied
    interval_text "six months" <- MUST appear verbatim in the cited provision
    operation     from the close of the financial year
    ---------------------------------------------------
    result        2026-09-30   <- DERIVED. Never retrieved. Never generated by a model.

The interval is checked against source. The arithmetic is deterministic. The result is shown with
its working. A fabricated figure still dies.

Run: python3 checker/derived_date.py
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, timedelta
from typing import Literal

DayCount = Literal["calendar", "clear"]
ServiceMode = Literal["hand", "electronic", "post", "courier", "speed_post", "registered_post"]

# Verbatim, from ICSI Secretarial Standards. These are the CITED SOURCES for the day-count rules
# below. Previously the clear-day arithmetic was asserted from reasoning with no authority behind
# it — the exact defect this product exists to prevent. Now the rule quotes the standard.
#
# SS-2 (General Meetings, revised, effective 1 Apr 2024), para 1.2.6:
SS2_CLEAR_DAYS = (
    "clear days in advance of the Meeting. For the purpose of reckoning twenty-one days clear "
    "Notice, the day of sending the Notice and the day of Meeting shall not be counted. Further "
    "in case the company sends the Notice by post or courier, an additional two days shall be "
    "provided for the service of Notice."
)
# SS-1 (Meetings of the Board, revised, effective 1 Apr 2024), para 1.3.6:
SS1_BOARD_NOTICE = (
    "least seven days before the date of the Meeting, unless the Articles prescribe a longer "
    "period. In case the company sends the Notice by speed post or by registered post, an "
    "additional two days shall be added for the service of Notice."
)
# Both standards add two days for physical service. Hand delivery and electronic service do not.
SERVICE_ADDEND_DAYS = 2
_POSTAL: frozenset[str] = frozenset({"post", "courier", "speed_post", "registered_post"})

_WORD_NUM = {
    "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "seven": 7,
    "eight": 8, "nine": 9, "ten": 10, "eleven": 11, "twelve": 12, "fifteen": 15,
    "twenty": 20, "twenty-one": 21, "thirty": 30, "forty-five": 45, "sixty": 60,
    "ninety": 90, "hundred and twenty": 120, "one hundred and twenty": 120,
}
_INTERVAL = re.compile(
    r"\b(\d+|" + "|".join(sorted(_WORD_NUM, key=len, reverse=True)) + r")\s+"
    r"(clear\s+)?(day|days|month|months|year|years)\b", re.I)


class IntervalNotInSource(ValueError):
    """The interval was not found verbatim in the cited provision. Never guess it."""


@dataclass(frozen=True)
class DerivedDate:
    result: date
    anchor: date
    anchor_label: str
    interval_text: str     # verbatim from the provision
    interval_value: int
    interval_unit: str
    day_count: DayCount
    citation: str
    quote: str             # the provision sentence, verbatim
    service_mode: ServiceMode = "hand"
    service_addend: int = 0

    def working(self) -> str:
        """The derivation, shown. This is what makes the result admissible."""
        cc = " (clear days — day of sending and day of Meeting both excluded)" if self.day_count == "clear" else ""
        lines = [f"{self.anchor.isoformat()} ({self.anchor_label}, supplied by you)",
                 f"  + {self.interval_text}{cc}  — verbatim from {self.citation}"]
        if self.service_addend:
            lines.append(f"  + {self.service_addend} days for service by {self.service_mode.replace('_', ' ')}"
                         f"  — {self.citation}")
        lines.append(f"  = {self.result.isoformat()}")
        return "\n".join(lines)


def _add_months(d: date, n: int) -> date:
    """Calendar-month addition, clamped to month end. 31 Mar + 6 = 30 Sep."""
    y, m = divmod((d.year * 12 + (d.month - 1)) + n, 12)
    m += 1
    last = (date(y + (m == 12), (m % 12) + 1, 1) - timedelta(days=1)).day
    return date(y, m, min(d.day, last))


def parse_interval(source_text: str) -> tuple[str, int, str, bool]:
    """(verbatim, value, unit, is_clear). Raises if no interval is stated in the source."""
    m = _INTERVAL.search(source_text)
    if not m:
        raise IntervalNotInSource(
            "No interval stated in the cited provision. The deadline cannot be derived; abstain.")
    raw, clear, unit = m.group(1), bool(m.group(2)), m.group(3).lower().rstrip("s")
    value = int(raw) if raw.isdigit() else _WORD_NUM[raw.lower()]
    return m.group(0).strip(), value, unit, clear


def derive(
    *,
    anchor: date,
    anchor_label: str,
    source_text: str,
    citation: str,
    day_count: DayCount = "calendar",
    service_mode: ServiceMode = "hand",
) -> DerivedDate:
    """Derive a statutory deadline. The interval MUST appear in source_text or this raises."""
    verbatim, value, unit, is_clear = parse_interval(source_text)
    if is_clear:
        day_count = "clear"

    # SS-1 1.3.6 / SS-2 1.2.6: physical service adds two days. Only applies to day-counted
    # notice periods, and only where the cited source actually states the addend.
    addend = 0
    if (service_mode in _POSTAL and unit == "day"
            and re.search(r"additional\s+two\s+days", source_text, re.I)):
        addend = SERVICE_ADDEND_DAYS

    if unit == "month":
        result = _add_months(anchor, value)
    elif unit == "year":
        result = _add_months(anchor, value * 12)
    elif day_count == "clear":
        # SS-2 1.2.6, verbatim: "the day of sending the Notice and the day of Meeting shall not be
        # counted." Dispatch 1 May + 21 clear days -> 2-22 May are the clear days, meeting 23 May.
        result = anchor + timedelta(days=value + 1 + addend)
    else:
        result = anchor + timedelta(days=value + addend)

    return DerivedDate(result, anchor, anchor_label, verbatim, value, unit,
                       day_count, citation, source_text.strip()[:300], service_mode, addend)


def verify(dd: DerivedDate, source_text: str) -> bool:
    """Re-check: the interval is in source, and the arithmetic reproduces. Used by the gate."""
    if dd.interval_text.lower() not in source_text.lower():
        return False
    return derive(anchor=dd.anchor, anchor_label=dd.anchor_label, source_text=source_text,
                  citation=dd.citation, day_count=dd.day_count,
                  service_mode=dd.service_mode).result == dd.result


# --- self-test ---------------------------------------------------------------

S96 = ("Every company shall in each year hold in addition to any other meetings, a general meeting "
       "as its annual general meeting ... and not more than fifteen months shall elapse between the "
       "date of one annual general meeting of a company and that of the next: Provided that ... shall "
       "hold its first annual general meeting within a period of nine months from the date of closing "
       "of the first financial year ... and in any other case, within a period of six months, from the "
       "date of closing of the financial year")
S137 = "shall be filed with the Registrar within thirty days of the date of annual general meeting"
SS2 = "Notice shall be given at least twenty-one " + SS2_CLEAR_DAYS


def _test() -> None:
    ok = fail = 0

    def check(c: bool, label: str) -> None:
        nonlocal ok, fail
        if c:
            ok += 1; print(f"[PASS] {label}")
        else:
            fail += 1; print(f"[FAIL] {label}")

    # The canonical case from TECHNICAL_PLAN_CORPORATE.md §0.
    agm = derive(anchor=date(2026, 3, 31), anchor_label="close of the financial year",
                 source_text="within a period of six months, from the date of closing of the financial year",
                 citation="s.96(1), Companies Act 2013")
    check(agm.result == date(2026, 9, 30), "s.96: 31 Mar 2026 + six months = 30 Sep 2026")
    check(agm.interval_text.lower().startswith("six month"), "s.96: interval taken verbatim from source")
    check("30 September" not in S96 and "2026-09-30" not in S96,
          "the result appears nowhere in the statute — which is the whole problem")
    check("supplied by you" in agm.working() and "verbatim" in agm.working(),
          "working shows anchor provenance and that the interval is sourced")

    # AOC-4 = AGM + 30 days.
    aoc4 = derive(anchor=date(2026, 9, 30), anchor_label="date the AGM was held",
                  source_text=S137, citation="s.137(1)")
    check(aoc4.result == date(2026, 10, 30), "s.137: AGM + thirty days = 30 Oct 2026")

    # Month-end clamping: 31 Aug + 6 months must not overflow into March.
    check(derive(anchor=date(2025, 8, 31), anchor_label="fy close",
                 source_text="within six months", citation="s.96").result == date(2026, 2, 28),
          "month arithmetic clamps to month end (31 Aug + 6m = 28 Feb)")

    # SS-2 clear days — both endpoints excluded.
    cd = derive(anchor=date(2026, 5, 1), anchor_label="date of dispatch",
                source_text=SS2, citation="SS-2 1.2.6")
    check(cd.day_count == "clear", "clear days detected from the source wording")
    check(cd.result == date(2026, 5, 23), "twenty-one clear days excludes both endpoints")
    check("day of sending the Notice and the day of Meeting shall not be counted" in SS2_CLEAR_DAYS,
          "clear-day rule now quotes SS-2 1.2.6 verbatim, not an assertion")

    # SS-2 1.2.6 second limb: physical service adds two days.
    post = derive(anchor=date(2026, 5, 1), anchor_label="date of dispatch", source_text=SS2,
                  citation="SS-2 1.2.6", service_mode="post")
    check(post.result == date(2026, 5, 25), "post service adds two days (23 May -> 25 May)")
    check(post.service_addend == 2 and "service by post" in post.working(),
          "service addend shown in the working")
    check(derive(anchor=date(2026, 5, 1), anchor_label="d", source_text=SS2,
                 citation="SS-2 1.2.6", service_mode="electronic").result == date(2026, 5, 23),
          "electronic service adds nothing")

    # SS-1 1.3.6: seven days board notice, +2 by speed/registered post.
    bd = derive(anchor=date(2026, 5, 1), anchor_label="date of dispatch",
                source_text=SS1_BOARD_NOTICE, citation="SS-1 1.3.6")
    check(bd.interval_value == 7 and bd.result == date(2026, 5, 8), "SS-1: seven days board notice")
    check(derive(anchor=date(2026, 5, 1), anchor_label="d", source_text=SS1_BOARD_NOTICE,
                 citation="SS-1 1.3.6", service_mode="registered_post").result == date(2026, 5, 10),
          "SS-1: registered post adds two days")

    # The addend fires only where the source states it — never assumed.
    check(derive(anchor=date(2026, 9, 30), anchor_label="agm", source_text=S137,
                 citation="s.137(1)", service_mode="post").service_addend == 0,
          "no addend where the cited source does not state one")

    # The gate: no interval in source => raise, never guess.
    try:
        derive(anchor=date(2026, 3, 31), anchor_label="fy close",
               source_text="The Board shall meet as often as necessary.", citation="x")
        check(False, "missing interval must raise")
    except IntervalNotInSource:
        check(True, "no interval in source raises rather than guessing a deadline")

    # Verification round-trip, and tamper detection.
    check(verify(agm, "within a period of six months, from the date of closing of the financial year"),
          "verify() reproduces the derivation from source")
    check(not verify(agm, "within a period of nine months from the date of closing"),
          "verify() rejects a result whose interval is not in the cited source")

    check(_WORD_NUM["fifteen"] == 15 and parse_interval(S96)[1] == 15,
          "s.96 first interval read as fifteen months (the AGM-to-AGM cap)")

    print(f"\n{ok}/{ok + fail} passed")
    if fail:
        raise SystemExit(1)


if __name__ == "__main__":
    _test()
